Added "`-fno-strict-aliasing`" to "set(warnings_flags_list" in CMake config file "cmake/modules/CompileOptionsCPlusPlus.cmake".
I just upgraded my system to Ubuntu 9.10; the version of GCC is now 4.4.1 (Ubuntu 4.4.1-4ubuntu9).  Now I get the following compilation error:

{{{
[  2%] Building CXX object src/qt-widgets/CMakeFiles/qt-widgets.dir/CreateFeatureDialog.o
cc1plus: warnings being treated as errors
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h: In member function ‘void GPlatesQtWidgets::CreateFeatureDialog::handle_create()’:
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:87: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/qt-widgets/CreateFeatureDialog.cc:957: note: initialized from here
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/system-fixes/boost/optional/optional.hpp:423: note: initialized from here
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/system-fixes/boost/optional/optional.hpp:423: note: initialized from here
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/utils/non_null_intrusive_ptr.h:94: error: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/system-fixes/boost/optional/optional.hpp:423: note: initialized from here
make[2]: *** [src/qt-widgets/CMakeFiles/qt-widgets.dir/CreateFeatureDialog.o] Error 1
}}}

This may or may not be a bug in GCC or a bug in BoostOptional:

 * http://lists.boost.org/Archives/boost/2009/05/151305.php
 * http://lists.boost.org/Archives/boost/2009/05/151318.php
 * http://lists.boost.org/Archives/boost/2009/05/151577.php
 * http://lists.boost.org/Archives/boost/2009/05/151581.php
 * http://lists.boost.org/Archives/boost/2009/07/153930.php

The version of BoostOptional in "`/usr/include`" is exactly the same as the version we've copied into "`system-fixes`", so there haven't been any recent fixes for this which we might be clobbering with our own version in `system-fixes`.

Hence, it seems the only way to fix this problem is to follow this advice:

{{{
Of course, one could just turn off strict aliasing for gcc, using the
-fno-strict-aliasing option. Doing so would put you in good company;
many large projects (including the Linux kernel, BSD, rtems, Python,
bjam(!), others that I don't recall off the top of my head) turn off
strict aliasing, with such reasons as the following cited

- the strict aliasing rules and their implications are arcane,

- the strict aliasing rules forbid idioms common in low-level system
programming type code,

- the methods for dealing with strict aliasing in such low-level
system code make the code harder to understand,

- the benefits derived from enabling strict aliasing are not worth the
headaches
}}}

 -- http://lists.boost.org/Archives/boost/2009/05/151318.php



git-svn-id: http://svn.gplates.org/projects/gplates/trunk@7554 e74ed31e-5968-4cd8-ac0b-be5e0f3b170c