Introduced the macro '`FREAD_OR_RETURN`' to check the return value of '`fread`' in the function '`load_tga_file`'.
The new version of G++ (4.4.1) was complaining:
{{{
[ 77%] Building CXX object src/file-io/CMakeFiles/file-io.dir/RasterReader.o
cc1plus: warnings being treated as errors
src/file-io/RasterReader.cc: In function ‘void<unnamed>::load_tga_file(const QString&, GPlatesPropertyValues::InMemoryRaster&, GPlatesFileIO::ReadErrorAccumulation&)’:
src/file-io/RasterReader.cc:103: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:104: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:107: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:115: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:116: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:117: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:118: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:119: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:122: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:123: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:124: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
src/file-io/RasterReader.cc:126: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result
make[2]: *** [src/file-io/CMakeFiles/file-io.dir/RasterReader.o] Error 1
}}}


git-svn-id: http://svn.gplates.org/projects/gplates/trunk@7571 e74ed31e-5968-4cd8-ac0b-be5e0f3b170c