Added "`-isystem /usr/include/qt4`" to "`set(warnings_flags_list`" in CMake config file "`cmake/modules/CompileOptionsCPlusPlus.cmake`'.
This is a temporary work-around for this compilation error:
{{{
 22%] Building CXX object src/qt-widgets/CMakeFiles/qt-widgets.dir/AboutDialog.o
cc1plus: warnings being treated as errors
In file included from /usr/include/qt4/QtGui/qbrush.h:50,
                 from /usr/include/qt4/QtGui/qpalette.h:47,
                 from /usr/include/qt4/QtGui/qwidget.h:48,
                 from /usr/include/qt4/QtGui/qdialog.h:45,
                 from /usr/include/qt4/QtGui/QDialog:1,
                 from .../trunk/src/qt-widgets/AboutDialog.h:29,
                 from .../trunk/src/qt-widgets/AboutDialog.cc:26:
/usr/include/qt4/QtGui/qtransform.h: In member function ‘QTransform& QTransform::operator*=(qreal)’:
/usr/include/qt4/QtGui/qtransform.h:260: error: comparing floating point with == or != is unsafe
/usr/include/qt4/QtGui/qtransform.h: In member function ‘QTransform& QTransform::operator/=(qreal)’:
/usr/include/qt4/QtGui/qtransform.h:276: error: comparing floating point with == or != is unsafe
/usr/include/qt4/QtGui/qtransform.h: In member function ‘QTransform& QTransform::operator+=(qreal)’:
/usr/include/qt4/QtGui/qtransform.h:283: error: comparing floating point with == or != is unsafe
/usr/include/qt4/QtGui/qtransform.h: In member function ‘QTransform& QTransform::operator-=(qreal)’:
/usr/include/qt4/QtGui/qtransform.h:299: error: comparing floating point with == or != is unsafe
make[2]: *** [src/qt-widgets/CMakeFiles/qt-widgets.dir/AboutDialog.o] Error 1
}}}

Observe that G++ ''should'' realise that "`qtransform.h`" is in the system headers directory, but for some reason it doesn't.  Hence, this hack is to '''tell''' G++ that "`/usr/include/qt4`" is a system header directory.

John has expressed a desire to fix this properly in the near future.


git-svn-id: http://svn.gplates.org/projects/gplates/trunk@7551 e74ed31e-5968-4cd8-ac0b-be5e0f3b170c