Simplified the interface of 'ReconstructionGeometryUtils::get_plate_id'.
The new version of G++ (4.4.1) on my system gave the following warning/error:
{{{
[ 53%] Building CXX object src/presentation/CMakeFiles/presentation.dir/ViewState.o
cc1plus: warnings being treated as errors
In file included from /homes/geo/jboyden/GPlates/++Code/2010/trunk/src/gui/ColourSchemeFactory.h:31,
                 from /homes/geo/jboyden/GPlates/++Code/2010/trunk/src/presentation/ViewState.cc:35:
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/gui/ColourSchemeFactory.h: In member function ‘boost::optional<GPlatesGui::Colour> GPlatesGui::GenericColourScheme<PropertyExtractorType>::get_colour(const GPlatesModel::ReconstructionGeometry&) const [with PropertyExtractorType = <unnamed>::PlateIdPropertyExtractor]’:
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/gui/ColourSchemeFactory.h:51: error: ‘plate_id’ may be used uninitialized in this function
/homes/geo/jboyden/GPlates/++Code/2010/trunk/src/gui/ColourSchemeFactory.h:51: note: ‘plate_id’ was declared here
make[2]: *** [src/presentation/CMakeFiles/presentation.dir/ViewState.o] Error 1
}}}

When examining this code, I realised that the interface of 'ReconstructionGeometryUtils::get_plate_id' had the following problems:
 1. It required a return-value parameter, which was the source of the compiler complaint (the compiler was complaining that the return-value parameter was uninitialised).  A possible solution would be to initialise that variable with an arbitrary value to placate the compiler, but this seemed like a poor solution.
 2. The interface was unnecessarily C-like (ie, a return value which indicates how the function behaved, and a return-value parameter which contains the actual return value) when it could be much more C++-like (using a '`boost:optional`' instead of a boolean return value and a return-value parameter).  In particular, the return-value would always be true when there were a value assigned to return-value parameter, and false otherwise; this correlates exactly with '`boost::optional`'.
 3. In "`gui/ColourSchemeFactory.h`' (the file about which the compiler initially complained), the calling code was unnecessarily awkward due to the function interface.
 4. Similarly, in the function definition, the code was of the idiomatically-awkward form:
{{{
    if (some condition false)
        return false;
    else
        return true;
}}}
 5. The idiomatic awkwardness was even more unnecessary since the "some condition" was actually whether a '`boost::optional`' had been assigned!  This could be simplifed to:
{{{
    return boost_optional_variable;
}}}

Changing the interface of 'ReconstructionGeometryUtils::get_plate_id' resulted in the simplification of both calling code and the code in the function definition.  John Cannon confirmed that these changes looked OK.


git-svn-id: http://svn.gplates.org/projects/gplates/trunk@7567 e74ed31e-5968-4cd8-ac0b-be5e0f3b170c